import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/ui/navbar";
import { cn } from "@/lib/utils";
import ChatWidget from "@/components/ui/chat-widget";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans", });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
        "min-h-screen bg-background font-sans antialiased",
        inter.variable
      )}>
        <header className="">
          <Navbar />
        </header>
        {children}
        <ChatWidget />
        <div className="mt-[50px] h-[400px] bg-primary text-white text-center py-4">
          <p>Footer</p>
        </div>
      </body>
    </html>
  );
}
